CREATE DATABASE BD_EMPRESA

USE BD_EMPRESA

CREATE TABLE Empleados
(
	ID INT IDENTITY(1,1),
	NombreEmpleado VARCHAR(100),
	ApellidoEmpleado VARCHAR(100),
	ComisionVentaEmpleado DECIMAL

	CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID)
);

CREATE TABLE Proveedores
(
	ID INT IDENTITY(1,1),
	NombreProveedor VARCHAR(100)

	CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID)
);

CREATE TABLE Categorias
(
	ID INT IDENTITY(1,1),
	NombreCategoria VARCHAR(100),
	DescripcionCategoria VARCHAR(200)

	CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID)
);

CREATE TABLE Productos
(
	ID INT IDENTITY(1,1),
	IdCategoria INT,
	NombreProducto VARCHAR(100),
	DescripcionProducto VARCHAR(200),
	UnidadesProducto INT,
	CostoProducto DECIMAL

	CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID)
	CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (IdCategoria) REFERENCES Categorias(ID)
);

CREATE TABLE Compras
(
	ID INT IDENTITY(1,1),
	FechaCompra DATE,
	IdProveedor INT,
	IdProducto INT,
	UnidadesCompra INT
	
	CONSTRAINT PK_COMPRAS PRIMARY KEY (ID)
	CONSTRAINT FK_COMPRAS_PROVEEDORES FOREIGN KEY (IdProveedor) REFERENCES Proveedores(ID),
	CONSTRAINT FK_COMPRAS_PRODUCTOS FOREIGN KEY (IdProducto) REFERENCES Productos(ID)
);

CREATE TABLE Ventas
(
	ID INT IDENTITY(1,1),
	FechaVenta DATE,
	IdProducto INT,
	UnidadesVenta INT,
	PrecioUnitarioVenta DECIMAL,
	PrecioTotalVenta DECIMAL,
	IdEmpleado INT
	
	CONSTRAINT PK_VENTAS PRIMARY KEY (ID),
	CONSTRAINT FK_VENTAS_PRODUCTOS FOREIGN KEY (IdProducto) REFERENCES Productos(ID),
	CONSTRAINT FK_VENTAS_EMPLEADOS FOREIGN KEY (IdEmpleado) REFERENCES Empleados(ID)
);
