
CREATE DATABASE BD_EMPRESA

USE BD_EMPRESA

CREATE TABLE EMPLEADOS
(
	ID_EMPLEADO INT IDENTITY(1,1),
	NOMBRE_EMPLEADO VARCHAR(50),
	APELLIDO_EMPLEADO VARCHAR(50),
	COMISIONVENTA_EMPLEADO DECIMAL

	CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE CATEGORIAS
(
	ID_CATEGORIA INT IDENTITY(1,1),
	NOMBRE_CATEGORIA VARCHAR(50),
	DESCRIPCION_CATEGORIA VARCHAR(50)

	CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE PRODUCTOS
(
	ID_PRODUCTO INT IDENTITY(1,1),
	ID_CATEGORIA INT,
	NOMBRE_PRODUCTO VARCHAR(50),
	DESCRIPCION_PRODUCTO VARCHAR(50),
	UNIDADES_PRODUCTO INT,
	COSTO_PRODUCTO DECIMAL

	CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO)
	CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);


CREATE TABLE PROVEEDORES
(
	ID_PROVEEDOR INT IDENTITY(1,1),
	NOMBRE_PROVEEDOR VARCHAR(50)

	CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR)
);

CREATE TABLE COMPRAS
(
	ID_COMPRA INT IDENTITY(1,1),
	FECHA_COMPRA DATE,
	ID_PROVEEDOR INT,
	ID_PRODUCTO INT,
	UNIDADES_COMPRA INT
	
	CONSTRAINT PK_COMPRAS PRIMARY KEY (ID_COMPRA)
	CONSTRAINT FK_COMPRAS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR),
	CONSTRAINT FK_COMPRAS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE VENTAS
(
	ID_VENTA INT IDENTITY(1,1),
	FECHA_VENTA DATE,
	ID_PRODUCTO INT,
	UNIDADES_VENTA INT,
	PRECIOUNITARIO_VENTA DECIMAL,
	PRECIOTOTAL_VENTA DECIMAL,
	ID_EMPLEADO INT
	
	CONSTRAINT PK_VENTAS PRIMARY KEY (ID_VENTA),
	CONSTRAINT FK_VENTAS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
	CONSTRAINT FK_VENTAS_EMPLEADOS FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);
