// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDES_Empresa.Models;

#nullable disable

namespace ProyectoDES_Empresa.Migrations
{
    [DbContext(typeof(EmpresaDBContext))]
    partial class EmpresaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Categoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DescripcionCategoria")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DescripcionCategoria = "Pinturas de exteriores",
                            NombreCategoria = "Exteriores"
                        },
                        new
                        {
                            ID = 2,
                            DescripcionCategoria = "pinturas de interiores",
                            NombreCategoria = "Interiores"
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Compra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesCompra")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Compras");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FechaCompra = new DateTime(2023, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdProducto = 1,
                            IdProveedor = 1,
                            UnidadesCompra = 5
                        },
                        new
                        {
                            ID = 2,
                            FechaCompra = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdProducto = 2,
                            IdProveedor = 2,
                            UnidadesCompra = 10
                        },
                        new
                        {
                            ID = 3,
                            FechaCompra = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdProducto = 3,
                            IdProveedor = 3,
                            UnidadesCompra = 7
                        },
                        new
                        {
                            ID = 4,
                            FechaCompra = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdProducto = 4,
                            IdProveedor = 4,
                            UnidadesCompra = 2
                        },
                        new
                        {
                            ID = 5,
                            FechaCompra = new DateTime(2023, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdProducto = 5,
                            IdProveedor = 5,
                            UnidadesCompra = 1
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Empleado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApellidoEmpleado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ComisionVentaEmpleado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ApellidoEmpleado = "Perez",
                            ComisionVentaEmpleado = 1.50m,
                            NombreEmpleado = "Juan"
                        },
                        new
                        {
                            ID = 2,
                            ApellidoEmpleado = "Torres",
                            ComisionVentaEmpleado = 1.0m,
                            NombreEmpleado = "Pamela"
                        },
                        new
                        {
                            ID = 3,
                            ApellidoEmpleado = "Gomez",
                            ComisionVentaEmpleado = 0.8m,
                            NombreEmpleado = "Patricia"
                        },
                        new
                        {
                            ID = 4,
                            ApellidoEmpleado = "Reyes",
                            ComisionVentaEmpleado = 1.2m,
                            NombreEmpleado = "Jonathan"
                        },
                        new
                        {
                            ID = 5,
                            ApellidoEmpleado = "Torres",
                            ComisionVentaEmpleado = 0.10m,
                            NombreEmpleado = "Mardoqueo"
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("CostoProducto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnidadesProducto")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CostoProducto = 124.99m,
                            DescripcionProducto = "Pintura para exteriores azul",
                            IdCategoria = 1,
                            NombreProducto = "Pintura azul",
                            UnidadesProducto = 100
                        },
                        new
                        {
                            ID = 2,
                            CostoProducto = 124.99m,
                            DescripcionProducto = "Pintura para interiores Roja",
                            IdCategoria = 2,
                            NombreProducto = "Pintura Roja",
                            UnidadesProducto = 100
                        },
                        new
                        {
                            ID = 3,
                            CostoProducto = 124.99m,
                            DescripcionProducto = "Pintura para exteriores blanca",
                            IdCategoria = 1,
                            NombreProducto = "Pintura blanca",
                            UnidadesProducto = 100
                        },
                        new
                        {
                            ID = 4,
                            CostoProducto = 124.99m,
                            DescripcionProducto = "Pintura para interiores verde",
                            IdCategoria = 2,
                            NombreProducto = "Pintura verde",
                            UnidadesProducto = 100
                        },
                        new
                        {
                            ID = 5,
                            CostoProducto = 124.99m,
                            DescripcionProducto = "Pintura para exteriores marron",
                            IdCategoria = 1,
                            NombreProducto = "Pintura marron",
                            UnidadesProducto = 100
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Proveedor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NombreProveedor = "Sherwin Williams"
                        },
                        new
                        {
                            ID = 2,
                            NombreProveedor = "Corona"
                        },
                        new
                        {
                            ID = 3,
                            NombreProveedor = "Comex"
                        },
                        new
                        {
                            ID = 4,
                            NombreProveedor = "Pinturas Americanas"
                        },
                        new
                        {
                            ID = 5,
                            NombreProveedor = "Pinturas genericas"
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Rol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            NombreRol = "Usuario"
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ClaveUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClaveUsuario = "1234",
                            CorreoUsuario = "admin@hotmail.com",
                            IdRol = 1
                        },
                        new
                        {
                            ID = 2,
                            ClaveUsuario = "1234",
                            CorreoUsuario = "lenin@hotmail.com",
                            IdRol = 2
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Venta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioTotalVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitarioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadesVenta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdProducto");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FechaVenta = new DateTime(2023, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEmpleado = 1,
                            IdProducto = 1,
                            PrecioTotalVenta = 3874.69m,
                            PrecioUnitarioVenta = 124.99m,
                            UnidadesVenta = 31
                        },
                        new
                        {
                            ID = 2,
                            FechaVenta = new DateTime(2023, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEmpleado = 2,
                            IdProducto = 2,
                            PrecioTotalVenta = 1374m,
                            PrecioUnitarioVenta = 124.99m,
                            UnidadesVenta = 11
                        },
                        new
                        {
                            ID = 3,
                            FechaVenta = new DateTime(2023, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEmpleado = 3,
                            IdProducto = 3,
                            PrecioTotalVenta = 609.95m,
                            PrecioUnitarioVenta = 124.99m,
                            UnidadesVenta = 5
                        },
                        new
                        {
                            ID = 4,
                            FechaVenta = new DateTime(2023, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEmpleado = 4,
                            IdProducto = 4,
                            PrecioTotalVenta = 124.99m,
                            PrecioUnitarioVenta = 124.99m,
                            UnidadesVenta = 1
                        },
                        new
                        {
                            ID = 5,
                            FechaVenta = new DateTime(2023, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEmpleado = 5,
                            IdProducto = 5,
                            PrecioTotalVenta = 249.98m,
                            PrecioUnitarioVenta = 124.99m,
                            UnidadesVenta = 2
                        });
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Compra", b =>
                {
                    b.HasOne("ProyectoDES_Empresa.Models.Producto", "Producto")
                        .WithMany("Compras")
                        .HasForeignKey("IdProducto");

                    b.HasOne("ProyectoDES_Empresa.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Producto", b =>
                {
                    b.HasOne("ProyectoDES_Empresa.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoDES_Empresa.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Venta", b =>
                {
                    b.HasOne("ProyectoDES_Empresa.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado");

                    b.HasOne("ProyectoDES_Empresa.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto");

                    b.Navigation("Empleado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProyectoDES_Empresa.Models.Producto", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
